### ISSUE TITLE
Multiple sources AND umbrella chart

### ISSUE THREAD

**Issue by StoffelCPR** [morey-tech/argo-cd-helm-values-demo#1]
Heyo,

I can't seem to make it work correctly. I've seen your youtube video and thought about asking here.

My goal would be to have an umbrella chart repository in git in which I can write a values file for general configurations.

umbrella-chart-repo/
|-- Chart.yaml
|-- values.yaml

and then Cluster/Stage specific repository containing congifurations specific to those. For ease of use I'd like to use values files here as to not need complex patching in kustomizations to do this:

argocd-repository/
|-- application/
|--|-- argocd-application.yaml
|--|-- values-stage.yaml

I'm trying to accomplish this by using multiple sources:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: ssh://git@gitaddress.example/argocd-repository.git
      targetRevision: HEAD
      ref: values
      
    - repoURL: ssh://git@gitaddress.example/umbrella-chart-repo.git
      path: keycloak
      targetRevision: HEAD
      helm:
        valueFiles:
        - values.yaml
        - $values/application/values-stage.yaml
    
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
```

As I said.. Nothing happens.. The umbrella charts' values file is sourced and shown in argocd. The remote values file is not used.
